# Generated by Django 4.2.1 on 2023-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_notesinfo_date_remove_notesinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
