# Generated by Django 4.2.1 on 2023-06-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_notesinfo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesinfo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
