# Generated by Django 4.2.1 on 2023-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_rename_notesinfo_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Heading',
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddField(
            model_name='notes',
            name='heading',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
