# Generated by Django 4.2.1 on 2023-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_remove_notes_heading_alter_notes_title_notes_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='heading',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
