# Generated by Django 4.2.1 on 2023-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_notes_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(),
        ),
    ]
